### ISSUE TITLE
[fix] 할 것

### ISSUE THREAD

**Issue by tjdanqkr** [JUST-CLICK-BANK/fe-click-bank#34]
<img width="931" alt="image" src="https://github.com/user-attachments/assets/5710da92-f964-4cc3-9914-b47d84eab7c0">

- [x] 이슈 템플릿
- [x] 풀리퀘 템플릿
- [x] 브런치 보호 룰

**Comment by tjdanqkr** [comment]
@ParkMiram  할것

**Comment by tjdanqkr** [comment]
@ParkMiram  이슈를 연결을 왜 안함?

**Comment by ParkMiram** [comment]
@tjdanqkr 어케함요?
